trello:
  api_key: "trello_api_key_here"
  user_token: "trello_token_with_read_access"

github:
  login: "your github username"
  password: "your github password"

  # username and repository where issues will be created,
  # such as mycompany/my-project
  username: "yourcompany"
  repository: "your-project"
